<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="86" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="86" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
      <class name="TestNG.UnitTestingWithTestNG">
        <test-method status="PASS" signature="Init()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="Init" is-config="true" duration-ms="15" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Init -->
        <test-method status="FAIL" signature="TestCase3()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="TestCase3" duration-ms="12" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [30] but found [-2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [30] but found [-2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at TestNG.UnitTestingWithTestNG.TestCase3(UnitTestingWithTestNG.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method status="PASS" signature="InitialiseRes()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="InitialiseRes" is-config="true" duration-ms="0" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitialiseRes -->
        <test-method status="PASS" signature="InitialiseRes()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="InitialiseRes" is-config="true" duration-ms="1" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitialiseRes -->
        <test-method status="FAIL" signature="TestCase3()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="TestCase3" duration-ms="3" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [30] but found [-2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [30] but found [-2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at TestNG.UnitTestingWithTestNG.TestCase3(UnitTestingWithTestNG.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method status="PASS" signature="InitialiseRes()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="InitialiseRes" is-config="true" duration-ms="0" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitialiseRes -->
        <test-method status="PASS" signature="TestCase1()[pri:1, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="TestCase1" duration-ms="4" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method status="PASS" signature="InitialiseRes()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="InitialiseRes" is-config="true" duration-ms="1" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitialiseRes -->
        <test-method status="PASS" signature="TestCase2()[pri:2, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="TestCase2" duration-ms="2" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
        <test-method status="PASS" signature="Stop()[pri:0, instance:TestNG.UnitTestingWithTestNG@51efea79]" name="Stop" is-config="true" duration-ms="0" started-at="2020-05-23T06:36:11Z" finished-at="2020-05-23T06:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Stop -->
      </class> <!-- TestNG.UnitTestingWithTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
